services:
  quiz0r:
    container_name: quiz0r

    build:
      context: .
      target: runner

    image: quiz0r:latest

    restart: unless-stopped

    ports:
      - "18081:3000"

    networks:
      - portainer_bridge # Verbindet den Container mit dem Netzwerk unten

    networks:
       portainer_bridge:
          name: bridge # Der echte Name des Standard-Netzwerks in Docker/Portainer
          external: true 

    environment:
      NODE_ENV: production
      DATABASE_URL: file:./prisma/data/quiz.db
      TZ: Europe/Berlin

    volumes:
      - quiz-data:/app/prisma/data
      - quiz-uploads:/app/public/uploads

volumes:
  quiz-data:
  quiz-uploads:
